export default {
    products:[{
        _id:'1',
        name:'Produit1',
        image: "/images/p1.png",
        category: "cars",
        price:60,
        brand:'ALPHAROMEO',
        rating : 4,
        numReviews:10,
        countInStock:0,
    },
    {
        _id:'2',
        name:'Produit2',
        category: "cars",
        image: "/images/p2.png",
        price:20,
        brand:'Dacia',
        rating : 3,
        numReviews:5,
        countInStock:12,
    },
    {
        _id:'3',
        name:'Produit3',
        category: "cars",
        image: "/images/p3.png",
        price:100,
        brand:'Volkswagen',
        rating : 4,
        numReviews:10,
        countInStock:4,
    },
    {
        _id:'4',
        name:'Produit4',
        category: "cars",
        image: "/images/p4.png",
        price:100,
        brand:'Toyota',
        rating : 4,
        numReviews:10,
        countInStock:10,
    },
    {
        _id:'5',
        name:'Produit5',
        category: "cars",
        image: "/images/p5.png",
        price:100,
        brand:'Audi',
        rating : 4,
        numReviews:10,
        countInStock:8,
    },
    {
        _id:'6',
        name:'Produit6',
        category: "cars",
        image: "/images/p6.png",
        price:40,
        brand:'Lamborghini',
        rating : 4,
        numReviews:10,
        countInStock:2,
    },
]
}